sector_a:
  use: 1
  coordinates: [[0.5, 0.5], [1.5, 0.5], [1.5, 1.5], [0.5, 1.5]]

sector_b:
  use: 1
  coordinates: [[4.5, 4.5], [5.5, 4.5], [5.5, 6.0], [4.5, 6.0]]

sector_c:
  use: 1
  coordinates: [[2.0, -2.0], [3.0, -2.0], [3.0, -3.0], [2.0, -3.0]]
